name: dart_git
version: 0.0.2
description: A Git client library
homepage: https://github.com/maks/dart-git
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  archive: 2.0.13
  diff_match_patch: 0.3.0
  intl: ^0.16.1
  logging: ^0.11.4
  utf: ^ 0.9.0+5 
  path: ^1.6.4
dev_dependencies:
  test:  1.14.1
